AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Streaming Bedrock Response with FastAPI on AWS Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Parameters:
  X_GITHUB_APP_ID:
    Type: Number
  X_GITHUB_APPS_CLIENT_ID:
    Type: String
  X_GITHUB_APPS_CLIENT_SECRET:
    Type: String
  OPENAI_API_KEY:
    Type: String
  SUPABASE_SERVICE_KEY:
    Type: String
  SUPABASE_URL:
    Type: String
  TAVILY_API_KEY:
    Type: String

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          X_GITHUB_APP_ID: !Ref X_GITHUB_APP_ID
          X_GITHUB_APPS_CLIENT_ID: !Ref X_GITHUB_APPS_CLIENT_ID
          X_GITHUB_APPS_CLIENT_SECRET: !Ref X_GITHUB_APPS_CLIENT_SECRET
          OPENAI_API_KEY: !Ref OPENAI_API_KEY
          SUPABASE_SERVICE_KEY: !Ref SUPABASE_SERVICE_KEY
          SUPABASE_URL: !Ref SUPABASE_URL
          TAVILY_API_KEY: !Ref TAVILY_API_KEY
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      Policies:
      - Statement:
        - Sid: BedrockInvokePolicy
          Effect: Allow
          Action:
          - bedrock:InvokeModelWithResponseStream
          Resource: '*'
      Tracing: Active
    Metadata:
      DockerContext: server
      Dockerfile: ../docker/Dockerfile.aws.lambda
      DockerTag: v1

Outputs:
  FastAPIFunctionUrl:
    Description: "Function URL for FastAPI function"
    Value: !GetAtt FastAPIFunctionUrl.FunctionUrl
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn