AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Streaming Bedrock Response with FastAPI on AWS Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Parameters:
  GitHubAppID:
    Type: Number
    Description: Github App Id
    Default: 1
  GithubAppsClientId:
    Type: String
    Description: Github App Id
    Default: 1
  APIIdentifier:
    Type: String
    Description: APIIdentifier
    Default: 1
  FastAPISecretKey:
    Type: String
    Description: FastAPISecretKey
    Default: 1
  GithubAppsClientSecret:
    Type: String
    Description: Github App Id
    Default: 1
  OpenAIAPIKey:
    Type: String
    Description: Github App Id
    Default: 1
  SupabaseServiceKey:
    Type: String
    Description: Github App Id
    Default: 1
  SupabaseUrl:
    Type: String
    Description: Github App Id
    Default: 1
  TavilyAPIKey:
    Type: String
    Description: Github App Id
    Default: 1

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          X_GITHUB_APP_ID: !Ref GitHubAppID
          X_GITHUB_APPS_CLIENT_ID: !Ref GithubAppsClientId
          X_GITHUB_APPS_CLIENT_SECRET: !Ref GithubAppsClientSecret
          API_IDENTIFIER: !Ref APIIdentifier
          FASTAPI_SECRET_KEY: !Ref: FastAPISecretKey
          OPENAI_API_KEY: !Ref OpenAIAPIKey
          SUPABASE_SERVICE_KEY: !Ref SupabaseServiceKey
          SUPABASE_URL: !Ref SupabaseUrl
          TAVILY_API_KEY: !Ref TavilyAPIKey
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      Policies:
      - Statement:
        - Sid: BedrockInvokePolicy
          Effect: Allow
          Action:
          - bedrock:InvokeModelWithResponseStream
          Resource: '*'
      Tracing: Active
    Metadata:
      DockerContext: server
      Dockerfile: ../docker/Dockerfile.aws.lambda
      DockerTag: v1

Outputs:
  FastAPIFunctionUrl:
    Description: "Function URL for FastAPI function"
    Value: !GetAtt FastAPIFunctionUrl.FunctionUrl
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn