AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Streaming Bedrock Response with FastAPI on AWS Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          API_URL: !Ref APIUrl
          WEB_URL: !Ref WebUrl
          X_GITHUB_APP_ID: !Ref GitHubAppID
          X_GITHUB_APPS_CLIENT_ID: !Ref GithubAppsClientId
          X_GITHUB_APPS_CLIENT_SECRET: !Ref GithubAppsClientSecret
          API_IDENTIFIER: !Ref APIIdentifier
          FASTAPI_SECRET_KEY: !Ref FastAPISecretKey
          OPENAI_API_KEY: !Ref OpenAIAPIKey
          GEMINI_API_KEY: !Ref GeminiAPIKey
          SUPABASE_SERVICE_KEY: !Ref SupabaseServiceKey
          SUPABASE_URL: !Ref SupabaseUrl
          GITHUB_TOKEN: !Ref GitHubToken
          TAVILY_API_KEY: !Ref TavilyAPIKey
          SQS_QUEUE_URL: !Ref SQSQueueUrl
          AUTH0_DOMAIN: !Ref Auth0Domain
          AUTH0_CLIENT_ID: !Ref Auth0ClientId
          AUTH0_CLIENT_SECRET: !Ref Auth0ClientSecret
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      Policies:
      - Statement:
        - Sid: BedrockInvokePolicy
          Effect: Allow
          Action:
          - bedrock:InvokeModelWithResponseStream
          Resource: '*'
      Tracing: Active
    Metadata:
      DockerContext: server
      Dockerfile: ../docker/Dockerfile.aws.lambda
      DockerTag: v1

  SQSSubscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          SUPABASE_SERVICE_KEY: !Ref SupabaseServiceKey
          SUPABASE_URL: !Ref SupabaseUrl
          GITHUB_TOKEN: !Ref GitHubToken
      Policies:
      - Statement:
        - Sid: BedrockInvokePolicy
          Effect: Allow
          Action:
          - bedrock:InvokeModelWithResponseStream
          Resource: '*'
        - Sid: SQSInvokePolicy
          Effect: Allow
          Action:
          - sqs:*
          Resource: '*'
      - SQSPollerPolicy:
          QueueName: 
            !Ref SQSQueueName
      Tracing: Active
    Metadata:
      Dockerfile: ../docker/Dockerfile.subscriber
      DockerContext: subscriber
      DockerTag: v1

Outputs:
  FastAPIFunctionUrl:
    Description: "Function URL for FastAPI function"
    Value: !GetAtt FastAPIFunctionUrl.FunctionUrl
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn

  SQSSubscriptionFunctionUrl:
    Description: "Function URL for SQS Subscriptio function"
    Value: !GetAtt SQSSubscriptionFunctionUrl.FunctionUrl
  SQSSubscriptionFunction:
    Description: "SQS Subscription Function Lambda Function ARN"
    Value: !GetAtt SQSSubscriptionFunction.Arn