AWSTemplateFormatVersion: '2010-09-09'
Description: 'Streaming Bedrock Response with FastAPI on AWS Lambda

  '
Globals:
  Function:
    Timeout: 300
Outputs:
  FastAPIFunction:
    Description: FastAPI Lambda Function ARN
    Value: FastAPIFunction.Arn
  FastAPIFunctionUrl:
    Description: Function URL for FastAPI function
    Value: FastAPIFunctionUrl.FunctionUrl
  SQSSubscriptionFunction:
    Description: SQS Subscription Function Lambda Function ARN
    Value: SQSSubscriptionFunction.Arn
  SQSSubscriptionFunctionUrl:
    Description: Function URL for SQS Subscriptio function
    Value: SQSSubscriptionFunctionUrl.FunctionUrl
Parameters:
  ApiIdentifier:
    Description: Parameter for ApiIdentifier
    Type: String
  ApiUrl:
    Description: Parameter for ApiUrl
    Type: String
  Auth0ClientId:
    Description: Parameter for Auth0ClientId
    Type: String
  Auth0ClientSecret:
    Description: Parameter for Auth0ClientSecret
    Type: String
  Auth0Domain:
    Description: Parameter for Auth0Domain
    Type: String
  AwsRegionName:
    Description: Parameter for AwsRegionName
    Type: String
  AwsSecretName:
    Description: Parameter for AwsSecretName
    Type: String
  CorsOriginWhitelist:
    Description: Parameter for CorsOriginWhitelist
    Type: String
  FastapiSecretKey:
    Description: Parameter for FastapiSecretKey
    Type: String
  GeminiApiKey:
    Description: Parameter for GeminiApiKey
    Type: String
  OpenaiApiKey:
    Description: Parameter for OpenaiApiKey
    Type: String
  RateLimitDuration:
    Description: Parameter for RateLimitDuration
    Type: String
  RateLimitEnabled:
    Description: Parameter for RateLimitEnabled
    Type: String
  RateLimitRequests:
    Description: Parameter for RateLimitRequests
    Type: String
  S3BucketName:
    Description: Parameter for S3BucketName
    Type: String
  SqsQueueUrl:
    Description: Parameter for SqsQueueUrl
    Type: String
  SupabaseServiceKey:
    Description: Parameter for SupabaseServiceKey
    Type: String
  SupabaseUrl:
    Description: Parameter for SupabaseUrl
    Type: String
  TavilyApiKey:
    Description: Parameter for TavilyApiKey
    Type: String
  WebUrl:
    Description: Parameter for WebUrl
    Type: String
  XGithubAppId:
    Description: Parameter for XGithubAppId
    Type: String
  XGithubAppsClientId:
    Description: Parameter for XGithubAppsClientId
    Type: String
  XGithubAppsClientSecret:
    Description: Parameter for XGithubAppsClientSecret
    Type: String
Resources:
  FastAPIFunction:
    Metadata:
      DockerContext: server
      DockerTag: v1
      Dockerfile: ../docker/Dockerfile.aws.lambda
    Properties:
      Environment:
        Variables:
          API_IDENTIFIER: !Ref 'ApiIdentifier'
          API_URL: !Ref 'ApiUrl'
          AUTH0_CLIENT_ID: !Ref 'Auth0ClientId'
          AUTH0_CLIENT_SECRET: !Ref 'Auth0ClientSecret'
          AUTH0_DOMAIN: !Ref 'Auth0Domain'
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          FASTAPI_SECRET_KEY: !Ref 'FastapiSecretKey'
          GEMINI_API_KEY: !Ref 'GeminiApiKey'
          GITHUB_TOKEN: GitHubToken
          OPENAI_API_KEY: !Ref 'OpenaiApiKey'
          SQS_QUEUE_URL: !Ref 'SqsQueueUrl'
          SUPABASE_SERVICE_KEY: !Ref 'SupabaseServiceKey'
          SUPABASE_URL: !Ref 'SupabaseUrl'
          TAVILY_API_KEY: !Ref 'TavilyApiKey'
          WEB_URL: !Ref 'WebUrl'
          X_GITHUB_APPS_CLIENT_ID: !Ref 'XGithubAppsClientId'
          X_GITHUB_APPS_CLIENT_SECRET: !Ref 'XGithubAppsClientSecret'
          X_GITHUB_APP_ID: !Ref 'XGithubAppId'
          AWS_SECRET_NAME: !Ref AWS_SECRET_NAME
          AWS_REGION_NAME: !Ref AWS_REGION_NAME
          S3_BUCKET_NAME: !Ref S3_BUCKET_NAME
          STATIC_URL: !Ref STATIC_URL
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      MemorySize: 512
      PackageType: Image
      Policies:
      - Statement:
        - Action:
          - bedrock:InvokeModelWithResponseStream
          Effect: Allow
          Resource: '*'
          Sid: BedrockInvokePolicy
      Tracing: Active
    Type: AWS::Serverless::Function
  SQSSubscriptionFunction:
    Metadata:
      DockerContext: subscriber
      DockerTag: v1
      Dockerfile: ../docker/Dockerfile.subscriber
    Properties:
      Environment:
        Variables:
          GITHUB_TOKEN: GitHubToken
          SUPABASE_SERVICE_KEY: !Ref 'SupabaseServiceKey'
          SUPABASE_URL: !Ref 'SupabaseUrl'
      FunctionUrlConfig:
        AuthType: NONE
      MemorySize: 512
      PackageType: Image
      Policies:
      - Statement:
        - Action:
          - bedrock:InvokeModelWithResponseStream
          Effect: Allow
          Resource: '*'
          Sid: BedrockInvokePolicy
        - Action:
          - sqs:*
          Effect: Allow
          Resource: '*'
          Sid: SQSInvokePolicy
      - SQSPollerPolicy:
          QueueName: SQSQueueName
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
