name: After Success

on:
  workflow_run:
    workflows: ["PR Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Success
        run: echo "Previous workflow was successful!"
