name: Build And Test

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/aws-preview.yml
      - server/**
      - petercat_utils/**
      - subscriber/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        run: |
          cd server

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest